/// Problem Details, as specified by RFC7807
struct ProblemDetails: Codable {
    /// A URI reference that identifies the problem type. This specification encourages that,
    /// when dereferenced, it provides human-readable documentation for the problem type.
    var type: String?
    /// A short, human-readable summary of the problem type. It should not change from
    /// occurrence to occurrence of the problem, except for purposes of localization.
    var title: String?
    /// The HTTP status code generated by the origin server for this occurrence of the problem.
    var status: Int?
    /// A human-readable explanation specific to this occurrence of the problem.
    var detail: String?
    /// A URI reference that identifies the specific occurrence of the problem.
    var instance: String?
}
