accessModifier: public
generate:
  - types
  - client
filter:
  operations:
    - "repos/list-tags"
    - "repos/get-latest-release"
    - "repos/get-release-by-tag"
    - "repos/get-content"
namingStrategy: idiomatic
