# This workflow will build and test the swift-package-registry-service
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: build-and-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Get swift version
      run: |
        swift --version
    - name: Trust macros and plugins
      run: |
        defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
        defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
